import { physicalData } from '../physical-scale.js';

const art = '地表艺术重建 · gpt-image-2.5-sunburst';
const reconstructed = 'AI 艺术重建 · 非实测地形';
const common = {
  date: '2026-09-12T12:00:00Z', panoramaCenter: 180, initialHeading: 180, initialPitch: 0,
  provenance: reconstructed, credit: art, referenceSolarAltitude: 25, nightFloor: .025,
  coordinateNote: '拟定观景坐标；地貌与全景朝向为示意，不能用于测量。',
};

// Every entry is one landing site. The key is the site id, `id` is the body it
// stands on, so a body may carry several sites as long as each key is unique.
// A body's default site is the one whose key equals its body id.
export const additionalLandingSites = Object.freeze({
  mars: {
    ...common, id:'mars', body:'Mars', name:'火星', title:'盖迪兹谷 · 夏普山麓', english:'GEDIZ VALLIS',
    radiusKm:physicalData.mars.radiusKm, latitude:-4.85, longitude:137.41,
    parent:'Sun', parentName:'太阳', parentRadiusKm:physicalData.sun.radiusKm, texture:'/surface/mars.webp', mobileTexture:'/surface/mars-4k.webp', textureWidth:8192,
    provenance:'好奇号 · 实拍拼接 / AI 补绘', credit:'NASA / JPL-Caltech / MSSS · PIA26410 · 缺测地面 gpt-image-2.5-sunburst',
    source:'https://www.jpl.nasa.gov/images/pia26410-curiositys-view-within-gediz-vallis-channel/',
    description:'好奇号在盖迪兹谷拍下的层状岩壁、碎石与古老河道，远处是夏普山的坡地。',
    notes:'原图由 2024 年 9 月 21–22 日的 341 张照片拼接，色彩经地球白平衡调整。上方已观测地形由原片合成保留；未拍到的脚下及车体区域，经实拍与全景构图双图参考生成补绘。天空替换为散射示意。坐标只定位盖迪兹谷附近，非精确车位；投影与朝向近似。火卫一、火卫二采用有来源的平均轨道，显示运动与凌日不用于真实日期预报。',
    atmosphere:'mars', solarDay:1.02749, initialHeading:100, panoramaCenter:180,
  },
  'mars-phoenix': {
    ...common, id:'mars', body:'Mars', name:'火星', title:'凤凰号着陆区 · 北极平原', english:'PHOENIX · VASTITAS BOREALIS',
    radiusKm:physicalData.mars.radiusKm, latitude:68.2188, longitude:234.2477,
    parent:'Sun', parentName:'太阳', parentRadiusKm:physicalData.sun.radiusKm, texture:'/surface/mars-phoenix.webp',
    provenance:'凤凰号实拍参考 · AI 重绘', credit:'NASA / JPL-Caltech / University of Arizona · PIA13804 · 地表重绘 gpt-image-2.5-sunburst',
    source:'https://www.jpl.nasa.gov/images/pia13804-mars-panorama-of-phoenix-landing-site-and-lander-deck',
    date:'2008-05-25T23:53:00Z',
    description:'多边形冻土在脚下铺开，浅槽里积着霜，远处是几乎完全平坦的北极平原。',
    notes:'地面多边形与浅槽形态依据凤凰号 2008 年实拍全景（PIA13804）参考重绘，整幅为新画面，未逐像素保留原片；着陆器本体、太阳板、气象桅杆与机械臂挖掘的沟槽没有重建。高纬地区日照特殊：该历元一个火星日内太阳高度角只在 2.7°–46.3° 之间，接近极昼，太阳不落。稀薄大气与天空由应用单独渲染，未烘焙进全景。',
    atmosphere:'mars', solarDay:1.02749, initialHeading:180, panoramaCenter:180, referenceSolarAltitude:25,
  },
  io: {
    ...common, id:'io', body:'Io', name:'木卫一', title:'朝木星侧 · 火山平原', english:'IO VOLCANIC PLAIN',
    radiusKm:physicalData.io.radiusKm, latitude:0, longitude:55,
    parent:'Jupiter', parentName:'木星', parentRadiusKm:physicalData.jupiter.radiusKm,
    texture:'/surface/io.webp',
    source:'https://science.nasa.gov/jupiter/jupiter-moons/io/facts/',
    description:'硫质沉积覆盖的平原与深色熔岩流交错，木星悬在朝向主星的一侧。',
    notes:'依据探测影像中的火山、硫质沉积与熔岩地貌重建。没有真实着陆照片，熔岩裂隙位置与亮度变化是艺术示意，不对应特定正在喷发的火山。使用 IAU 东经坐标，轨道与姿态独立计算，未额外加入非刚体物理天平动。落点在距次木星点约 55° 处，木星高度角约 34°，不在天顶。',
    solarDay:1.77, activity:'lava', initialHeading:235, panoramaCenter:180,
  },
  'io-subjovian': {
    ...common, id:'io', body:'Io', name:'木卫一', title:'次木星点 · 火山口边缘', english:'SUB-JOVIAN PATERA RIM',
    radiusKm:physicalData.io.radiusKm, latitude:0, longitude:0,
    parent:'Jupiter', parentName:'木星', parentRadiusKm:physicalData.jupiter.radiusKm,
    texture:'/surface/io-subjovian.webp',
    provenance:'次木星点 · AI 艺术重建', credit:'地表艺术重建 · gpt-image-2.5-sunburst · 材质参考同天体现有落点',
    source:'https://science.nasa.gov/jupiter/jupiter-moons/io/facts/',
    description:'浅碗状火山口的边缘，硫质地面泛着黄与灰绿，木星几乎就在天顶。',
    notes:'落点取在次木星点：木星高度角 89.1°–90.0°、视直径 19.1°–19.3°，在一个自转周期内几乎不动，与 55°E 落点的 34.0° 互为对照。**站在次木星点上，太阳每个公转周期都会从木星背后经过，形成一次周期性日食**，此时地表明显变暗；「寻找日照」会跳过这些时刻，不会把日食当成日照。落点不指代某座已命名火山，碗状凹陷与熔岩裂隙位置为艺术示意。硫质沉积与玄武岩的色调参考同天体现有落点素材，地形为新画面。',
    date:'2026-09-13T20:48:57Z', solarDay:1.77, activity:'lava', initialHeading:180, panoramaCenter:180, initialPitch:10,
  },
  titan: {
    ...common, id:'titan', body:'Titan', name:'土卫六', title:'惠更斯着陆区', english:'HUYGENS LANDING REGION',
    radiusKm:physicalData.titan.radiusKm, latitude:-10.3, longitude:192.3,
    parent:'Saturn', parentName:'土星', parentRadiusKm:physicalData.saturn.radiusKm,
    texture:'/surface/titan.webp',
    source:'https://www.esa.int/ESA_Multimedia/Images/2005/01/First_colour_view_of_Titan_s_surface',
    description:'浓厚的橙色雾霾笼罩平原，圆润的水冰卵石散布在暗色沉积物上。',
    notes:'依据惠更斯号照片的地貌特征进行文生图重建，没有逐像素沿用原片。着陆区并非甲烷湖面。大气为可见光散射示意，遮蔽星空与土星圆面；太阳只表现为模糊辉光。1900—2100 年的轨道采用 JPL SAT441，姿态独立采用 IAU 系数；大气散射并非完整辐射传输。',
    atmosphere:'titan', solarDay:15.98, obscuredParent:true, referenceSolarAltitude:20,
  },
  enceladus: {
    ...common, id:'enceladus', body:'Enceladus', name:'土卫二', title:'南极 · 虎纹裂缝', english:'SOUTH POLAR FRACTURES',
    radiusKm:physicalData.enceladus.radiusKm, latitude:-75, longitude:30,
    parent:'Saturn', parentName:'土星', parentRadiusKm:physicalData.saturn.radiusKm,
    texture:'/surface/enceladus.webp',
    source:'https://science.nasa.gov/mission/cassini/science/enceladus/',
    description:'水冰山脊被长裂缝切开，远处的冰粒喷流从南极地形上方伸向太空。',
    notes:'虎纹裂缝与喷流有卡西尼号观测依据，近地视野和喷口位置为艺术重建。喷流运动是展示近似。1900—2100 年轨道采用 JPL SAT441，姿态独立采用 IAU 系数，未额外模拟物理天平动；土星环按赤道平面绘制，在这里接近侧视，不是横跨天空的宽环。',
    solarDay:1.371, activity:'ice', initialHeading:180, referenceSolarAltitude:10,
  },
  pluto: {
    ...common, id:'pluto', body:'Pluto', name:'冥王星', title:'斯普特尼克平原边缘', english:'SPUTNIK PLANITIA MARGIN',
    radiusKm:physicalData.pluto.radiusKm, latitude:18, longitude:178,
    parent:'Charon', parentName:'冥卫一', parentRadiusKm:physicalData.charon.radiusKm,
    texture:'/surface/pluto.webp',
    source:'https://www.nasa.gov/missions/nasa-video-soars-over-plutos-majestic-mountains-and-icy-plains/',
    description:'氮冰平原与水冰山脉相接，远日世界的地平线向两侧展开。',
    notes:'依据新视野号地貌资料重建，没有真实着陆照片或逐像素高程还原。这里在背向冥卫一的一侧，冥卫一位于地平线下。太阳按实际视大小显示，曝光为展示调整；稀薄大气的微弱近地霾层为示意。1900—2100 年的冥王星与冥卫一位置采用 JPL PLU060；自转独立计算，未额外模拟物理天平动。',
    atmosphere:'pluto', solarDay:6.388, referenceSolarAltitude:20,
  },
  'pluto-charonface': {
    ...common, id:'pluto', body:'Pluto', name:'冥王星', title:'朝冥卫一高地', english:'CHARON-FACING TERRAIN',
    radiusKm:physicalData.pluto.radiusKm, latitude:12, longitude:0,
    parent:'Charon', parentName:'冥卫一', parentRadiusKm:physicalData.charon.radiusKm,
    texture:'/surface/pluto-charonface.webp',
    provenance:'朝冥卫一 · AI 艺术重建', credit:'地表艺术重建 · gpt-image-2.5-sunburst · 材质参考同天体现有落点',
    source:'https://www.nasa.gov/missions/new-horizons/plutos-big-moon-charon-reveals-a-colorful-and-violent-history/',
    description:'更古老、更粗糙的冰质高地，冥卫一几乎固定在头顶。',
    notes:'冥王星与冥卫一互相潮汐锁定。此落点在朝冥卫一的半球：冥卫一高度角约 78°、视直径约 3.8°，一个自转周期内几乎不动；现有 178°E 落点位于背侧，冥卫一高度角 −72.7°，永不升起。两点互为对照。近地地貌为艺术重建，冰质色调参考同天体现有落点素材。1900—2100 年位置采用 JPL PLU060。',
    atmosphere:'pluto', solarDay:6.388, initialPitch:10, referenceSolarAltitude:20,
  },
  miranda: {
    ...common, id:'miranda', body:'Miranda', name:'天卫五', title:'维罗纳断崖附近', english:'VERONA RUPES REGION',
    radiusKm:physicalData.miranda.radiusKm, latitude:-18, longitude:316,
    parent:'Uranus', parentName:'天王星', parentRadiusKm:physicalData.uranus.radiusKm,
    texture:'/surface/miranda.webp',
    source:'https://science.nasa.gov/uranus/moons/miranda/',
    description:'层状冰岩断崖从碎裂的平原升起，崖脚散落着棱角分明的坡积物。',
    notes:'旅行者 2 号影像提供地貌依据，近地轮廓、崖高和距离为艺术构建，不是测量模型。使用 IAU 极轴与自转相位，包括主要章动项；1900—2100 年轨道独立采用 JPL URA184；落点地形、姿态和时标近似仍不适用于精确日食预报。**这里的季节以十年计**：天王星倾角约 98°，天卫五跟着它绕太阳转，落点会连续多年见不到太阳——2026 年前后太阳高度角整日都在 −32° 与 −4° 之间，2085 年前后正午可到约 80°。默认日期只是资料时刻，从太阳系降落时继承当前模拟时间；在这些年份里「寻找日照」找不到日照是正确结果，不是故障。',
    solarDay:1.414, initialPitch:9, referenceSolarAltitude:15,
  },
  mercury: {
    ...common, id:'mercury', body:'Mercury', name:'水星', title:'卡洛里盆地 · 内侧平原', english:'CALORIS BASIN PLAINS',
    radiusKm:physicalData.mercury.radiusKm, latitude:30, longitude:160,
    parent:'Sun', parentName:'太阳', parentRadiusKm:physicalData.sun.radiusKm, texture:'/surface/mercury.webp',
    source:'https://science.nasa.gov/mercury/facts/',
    description:'古老火山平原上的撞击坑、褶皱山脊与灰褐色碎岩，远处是盆地边缘的低山。',
    notes:'信使号等轨道影像提供地貌依据，落地全景为艺术重建。水星只有极稀薄的外逸层，没有蓝天、云雾或风沙。自转约 58.65 地球日，太阳日约 176 地球日；太阳视大小随椭圆轨道变化。表面不模拟成熔岩海。',
    solarDay:176, referenceSolarAltitude:20,
  },
  'mercury-pole': {
    ...common, id:'mercury', body:'Mercury', name:'水星', title:'北极 · 永久阴影区边缘', english:'NORTH POLAR TERRAIN',
    radiusKm:physicalData.mercury.radiusKm, latitude:88, longitude:0,
    parent:'Sun', parentName:'太阳', parentRadiusKm:physicalData.sun.radiusKm, texture:'/surface/mercury-pole.webp',
    provenance:'北极 · AI 艺术重建', credit:'地表艺术重建 · gpt-image-2.5-sunburst · 材质参考同天体现有落点',
    source:'https://science.nasa.gov/mercury/facts/',
    description:'太阳贴着地平线缓慢移动，近处的浅坑内终年不见日光。',
    notes:'高纬度日照极特殊：按本项目星历复算，太阳高度角在整个约 176 地球日的太阳日内都只在 −2.0° 至 +2.0° 之间，太阳视直径同时由 1.72° 缩到 1.14°，一年绕地平线一圈而不是升起落下。雷达探测到的水冰沉积埋藏在永久阴影坑内，不显示为地表霜层，全景中也没有冰面反光。近地地貌为艺术重建，灰褐色调参考同天体现有落点素材。',
    solarDay:176, referenceSolarAltitude:1, daylightAltitude:1.2, initialHeading:180, panoramaCenter:180,
  },
  'moon-farside': {
    ...common, id:'moon', body:'Moon', name:'月球', title:'天河基地 · 冯·卡门坑', english:'STATIO TIANHE · VON KÁRMÁN',
    radiusKm:physicalData.moon.radiusKm, latitude:-45.4446, longitude:177.5991,
    parent:'Earth', parentName:'地球', parentRadiusKm:physicalData.earth.radiusKm,
    texture:'/surface/moon-farside.webp',
    date:'2019-01-03T02:26:00Z',
    provenance:'背面平原 · AI 艺术重建', credit:'地貌依据 CNSA 嫦娥四号 / 玉兔二号公开影像描述 · 着陆点定位论文 · 地表艺术重建 gpt-image-2.5-sunburst',
    source:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6760200',
    description:'南极-艾特肯盆地内的玄武岩平原，环顾四周看不到地球。',
    notes:'嫦娥四号于 2019-01-03 02:26 UTC 着陆在冯·卡门坑底，是人类第一次在月球背面着陆。落点坐标 177.5991°E / 45.4446°S 出自着陆点定位论文，非推测位置。地球在这里整月不升起：按本项目星历与 IAU 姿态复算，地球高度角在一个朔望月内只在 −51.3° 至 −37.2° 之间，永远在地平线下；近侧哈德利-亚平宁落点的地球高度角是 +68.3°。近地地貌为艺术重建，依据冯·卡门坑玄武岩平原的资料描述，没有逐像素沿用玉兔二号影像。',
    solarDay:29.53, initialHeading:180, panoramaCenter:180,
  },
  'europa-subjovian': {
    ...common, id:'europa', body:'Europa', name:'木卫二', title:'次木星点 · 双脊冰原', english:'SUB-JOVIAN DOUBLE RIDGES',
    radiusKm:physicalData.europa.radiusKm, latitude:0, longitude:0,
    parent:'Jupiter', parentName:'木星', parentRadiusKm:physicalData.jupiter.radiusKm,
    texture:'/surface/europa-subjovian.webp',
    provenance:'次木星点 · AI 艺术重建', credit:'地表艺术重建 · gpt-image-2.5-sunburst · 材质参考同天体现有落点',
    source:'https://www.jpl.nasa.gov/missions/europa-lander/',
    description:'笔直的双脊横过冰面，木星几乎就在天顶。',
    notes:'落点取在次木星点：木星高度角 87.3°–89.4°、视直径 11.9°–12.1°，一个自转周期内几乎不动；现有 62°E 落点的木星高度角只有 27.0°，两点互为对照。**站在次木星点上，太阳每个公转周期都会从木星背后经过，形成一次周期性日食**，此时地表明显变暗；「寻找日照」会跳过这些时刻，不会把日食当成日照。双脊与暗色纹路的位置为艺术示意，非实测裂隙图。使用 IAU 东经坐标，轨道与自转独立计算，未额外建模非刚体物理天平动。',
    solarDay:3.55, initialHeading:180, panoramaCenter:180, initialPitch:10,
  },
  charon: {
    ...common, id:'charon', body:'Charon', name:'冥卫一', title:'赤道峡谷带 · 朝冥王星侧', english:'EQUATORIAL CANYON BELT',
    radiusKm:physicalData.charon.radiusKm, latitude:2, longitude:0,
    parent:'Pluto', parentName:'冥王星', parentRadiusKm:physicalData.pluto.radiusKm,
    texture:'/surface/charon.webp',
    date:'2026-09-19T22:49:00Z',
    provenance:'赤道峡谷带 · AI 艺术重建', credit:'地貌依据 NASA 新视野号影像描述 · 地表艺术重建 gpt-image-2.5-sunburst',
    source:'https://www.nasa.gov/missions/new-horizons/plutos-big-moon-charon-reveals-a-colorful-and-violent-history/',
    description:'断裂的冰质峡谷从脚下延伸，冥王星几乎固定在头顶。',
    notes:'落点在朝冥王星的一侧：冥王星高度角 88.4°、视直径 7.2°，一个自转周期内几乎不动（互相潮汐锁定）。赤道峡谷带依据新视野号影像的地貌描述重建，崖高、走向与宽度不是测量值。冥卫一北半球的暗红色极冠（Mordor Macula）不在本落点视野内。1900—2100 年位置采用 JPL PLU060。',
    solarDay:6.388, initialPitch:10, referenceSolarAltitude:20,
  },
  venus: {
    ...common, id:'venus', body:'Venus', name:'金星', title:'金星 13 号着陆区 · 腓比区东侧', english:'VENERA 13 · EAST OF PHOEBE REGIO',
    radiusKm:physicalData.venus.radiusKm, latitude:-7.5, longitude:303,
    parent:'Sun', parentName:'太阳', parentRadiusKm:physicalData.sun.radiusKm, texture:'/surface/venus.webp',
    date:'2026-12-11T06:00:00Z',
    provenance:'金星 13 号实拍参考 · AI 重绘', credit:'苏联金星 13 号着陆全景 · USSR / NASA 公有领域 · 地表重绘 gpt-image-2.5-sunburst',
    source:'https://commons.wikimedia.org/wiki/File:V13_vg261_262.tif',
    description:'层状岩板铺满地面，暗褐色土壤里散着棱角碎石，浓厚的云把光散成一片均匀的赭黄。',
    notes:'金星 13 号 1982 年 3 月 1 日在南纬 7.5°、东经 303°（腓比区东侧）着陆，本落点即其着陆区。地面形态依据它拍下的可见光彩色全景参考重绘，整幅为新画面、未逐像素保留原片，照片中的着陆器硬件（齿状环、镜头盖、条纹标尺、天线）没有重建；参考片只覆盖约 40° 竖直视野，脚下没有实拍，按同一材质延续。金星大气为浓厚硫酸云：天空是均匀的赭黄漫射光，看不到太阳圆面、星空或任何其它天体，太阳只表现为云内一块略亮的光斑，该渲染是展示近似而不是辐射传输计算。一个太阳日约 116.75 地球日，落点处太阳高度角在 84.5° 与 −81.0° 之间变化；太阳视直径约 0.741°，约为地球上的 1.4 倍。金星自转逆行，太阳从西边升起。',
    atmosphere:'venus', solarDay:116.75, referenceSolarAltitude:60, initialHeading:180, panoramaCenter:180,
  },
  ceres: {
    ...common, id:'ceres', body:'Ceres', name:'谷神星', title:'奥卡托撞击坑 · 盐类亮斑', english:'OCCATOR CRATER · CEREALIA FACULA',
    radiusKm:physicalData.ceres.radiusKm, latitude:19.7, longitude:239.6,
    parent:'Sun', parentName:'太阳', parentRadiusKm:physicalData.sun.radiusKm, texture:'/surface/ceres.webp',
    date:'2026-09-18T00:20:25Z',
    provenance:'黎明号实拍参考 · AI 重绘', credit:'NASA / JPL-Caltech / UCLA / MPS-DLR-IDA · PIA21924 与 PIA24021 · 地表重绘 gpt-image-2.5-sunburst',
    source:'https://www.jpl.nasa.gov/images/pia21924-mosaic-of-cerealia-facula-in-occator-crater',
    description:'暗灰色坑底铺着细碎撞击碎屑，不远处升起一片白色的盐壳，像被压碎的脏雪一样反光。',
    notes:'落点取奥卡托撞击坑中央的 Cerealia Facula（亮斑），坐标 19.7°N / 239.6°E 出自 JPL 对该拼图的说明（坑本身约 20°N / 239°E）。亮斑是钠碳酸盐与氯化铵的盐壳，按反光材质表现，因此随日照变化，不设为自发光。地面形态依据黎明号低高度轨道拼图参考重绘（PIA21924 提供盐壳材质与碎裂结构，PIA24021 用于核对暗色坑底与盐壳的反差），整幅为新画面、未逐像素保留输入，也未沿用其俯视视角、取景与假彩色处理。谷神星没有可分辨的主星：太阳视直径约 0.199°，仅为地球所见的 0.37 倍，天空中没有可分辨的其它天体（火星、木星在此距离下视直径均小于 0.02°），也没有大气。一个自转周期约 9.074 小时，落点处太阳高度角在此周期内于 −73.35° 与 +67.24° 之间变化；默认资料的太阳高度角约 21.7°。1900—2100 年位置取随站发布的 Horizons 谷神星年历（201 个年份包），范围外回退到 JPL SBDB 的固定平均椭圆——那条约在历元外偏差数百角分，只作范围外近似。',
    solarDay:0.378083, referenceSolarAltitude:22, initialHeading:180, panoramaCenter:180,
  },
});

// A body is landable when it owns at least one site; several sites may share one.
export const landableBodyIds = Object.freeze([
  ...new Set(['moon', 'europa', ...Object.values(additionalLandingSites).map(site => site.id)]),
]);
