const rock = {
  high: null,
  tilt: 0,
  spin: 0.022,
  closeName: "观测地表",
};

export const additionalBodies = [
  {
    ...rock,
    id: "pluto",
    body: "Pluto",
    name: "冥王星",
    english: "PLUTO",
    category: "柯伊伯带 / 矮行星",
    group: "others",
    color: "#c9b8a8",
    texture: "pluto",
    high: "4k_pluto.jpg",
    radius: 0.7,
    orbit: 72,
    tilt: 119.6,
    viewUv: [0.51, 0.6],
    description:
      "海王星之外的冰质世界。明亮的氮冰平原与深色高地相邻，冥卫一与它共同绕着两者之间的质心运行。",
    facts: [
      ["平均半径", "1,188", "km"],
      ["公转周期 · 约", "248", "年"],
      ["区域", "柯伊伯带", ""],
      ["分类", "矮行星", ""],
    ],
    feature: "氮冰平原与冰山",
    featureText:
      "斯普特尼克平原的氮冰在漫长时间尺度上缓慢流动，水冰构成坚硬的山地。",
    caption: "冥王星冰原",
    detail: "NASA 球面地图 / 缺测区为低细节填色",
    source: "dwarf-planets/pluto/facts/",
  },
  {
    ...rock,
    id: "ceres",
    name: "谷神星",
    english: "CERES",
    category: "小行星带 / 矮行星",
    group: "others",
    color: "#b3b5b1",
    texture: "ceres",
    high: "4k_ceres.jpg",
    radius: 0.46,
    orbit: 27.2,
    tilt: 4,
    orbitDays: 1682,
    orbitPhase: 2.7,
    inclination: 10.6,
    description:
      "小行星带中最大的天体，也是其中唯一的矮行星。灰暗的撞击地貌间，散布着醒目的明亮盐类沉积。",
    facts: [
      ["平均半径 · 约", "470", "km"],
      ["公转周期 · 约", "4.6", "年"],
      ["区域", "小行星带", ""],
      ["探测任务", "黎明号", ""],
    ],
    feature: "撞击坑与盐类亮斑",
    featureText:
      "奥卡托撞击坑中的亮斑与含盐物质有关，记录了谷神星内部水活动的历史。",
    caption: "谷神星地表",
    detail: "黎明号影像 / 撞击坑与亮斑",
    source: "dwarf-planets/ceres/facts/",
  },
  {
    ...rock,
    id: "vesta",
    name: "灶神星",
    english: "VESTA",
    category: "小行星带 / 小行星",
    group: "others",
    color: "#b5aba2",
    texture: "vesta",
    radius: 0.36,
    orbit: 25.6,
    tilt: 27.5,
    shape: [1, 0.8, 0.92],
    orbitDays: 1325,
    orbitPhase: 5.1,
    inclination: 7.1,
    description:
      "一颗保存着早期太阳系历史的岩石天体。它曾发生内部熔融，南半球的巨大撞击留下了深刻痕迹。",
    facts: [
      ["平均直径 · 约", "525", "km"],
      ["公转周期 · 约", "3.6", "年"],
      ["区域", "小行星带", ""],
      ["探测任务", "黎明号", ""],
    ],
    feature: "古老盆地与沟槽",
    featureText:
      "巨大的南极撞击盆地与环绕赤道的沟槽，见证了这颗天体的碰撞历史。",
    caption: "灶神星地貌",
    detail: "黎明号影像 / 外形为近似椭球",
    source: "solar-system/asteroids/4-vesta/",
  },
  {
    ...rock,
    id: "moon",
    body: "Moon",
    name: "月球",
    english: "MOON",
    category: "地球 / 天然卫星",
    parent: "earth",
    color: "#c8c8c4",
    texture: "moon",
    high: "4k_moon.jpg",
    radius: 0.32,
    orbit: 3.6,
    period: 27.322,
    orbitPhase: 0.8,
    inclination: 5.1,
    description:
      "地球唯一的天然卫星。暗色月海与明亮高地铺展在古老地表，它的自转与公转相互同步。",
    facts: [
      ["平均半径", "1,737", "km"],
      ["绕地周期 · 约", "27.3", "天"],
      ["所属天体", "地球", ""],
      ["自转状态", "潮汐锁定", ""],
    ],
    feature: "月海与撞击射纹",
    featureText:
      "月海是古老的玄武岩平原。晨昏线掠过时，坑壁与高地的明暗逐渐改变。",
    caption: "月球地表",
    detail: "月海 / 高地 / 撞击射纹",
    source: "moon/facts/",
  },
  {
    ...rock,
    id: "phobos",
    name: "火卫一",
    english: "PHOBOS",
    category: "火星 / 天然卫星",
    parent: "mars",
    color: "#9f9385",
    texture: "phobos",
    radius: 0.19,
    orbit: 2.25,
    shape: [1, 0.81, 0.67],
    period: 0.319,
    orbitPhase: 2.2,
    inclination: 1.1,
    description:
      "紧贴火星运行的小型卫星。它的形状不规则，巨大的斯蒂克尼撞击坑占据了表面相当大的一部分。",
    facts: [
      ["平均半径 · 约", "11", "km"],
      ["绕火周期 · 约", "7.7", "小时"],
      ["所属天体", "火星", ""],
      ["自转状态", "潮汐锁定", ""],
    ],
    feature: "撞击坑与细长沟槽",
    featureText: "暗色风化层覆盖着坑洼表面。沟槽与撞击坑属于长期保存的地貌。",
    caption: "火卫一地表",
    detail: "探测影像合成 / 外形为近似椭球",
    source: "mars/moons/phobos/",
  },
  {
    ...rock,
    id: "io",
    name: "木卫一",
    english: "IO",
    category: "木星 / 火山卫星",
    parent: "jupiter",
    color: "#ded18b",
    texture: "io",
    radius: 0.43,
    orbit: 4.6,
    period: 1.769,
    orbitPhase: 0.5,
    inclination: 0.04,
    description:
      "太阳系火山活动最旺盛的世界。木星与其它卫星的引力拉扯使内部受热，硫质沉积染出鲜明色彩。",
    facts: [
      ["平均半径", "1,821", "km"],
      ["绕木周期 · 约", "1.77", "天"],
      ["所属天体", "木星", ""],
      ["主要活动", "火山喷发", ""],
    ],
    feature: "火山与硫质平原",
    featureText: "火山口与熔岩不断改变局部地表，羽状喷发将物质送向高空。",
    caption: "木卫一火山世界",
    detail: "探测影像合成 / 火山热点为动态示意",
    source: "jupiter/moons/io/",
  },
  {
    ...rock,
    id: "europa",
    name: "木卫二",
    english: "EUROPA",
    category: "木星 / 冰质卫星",
    parent: "jupiter",
    color: "#d6c6ad",
    texture: "europa",
    radius: 0.39,
    orbit: 6.2,
    period: 3.551,
    orbitPhase: 2.2,
    inclination: 0.47,
    description:
      "纵横交错的暗色裂纹划过明亮冰壳。多种观测证据表明，冰层之下可能存在覆盖全球的液态海洋。",
    facts: [
      ["平均半径", "1,561", "km"],
      ["绕木周期 · 约", "3.55", "天"],
      ["所属天体", "木星", ""],
      ["表面成分", "水冰", ""],
    ],
    feature: "冰壳裂纹与混沌地形",
    featureText:
      "裂纹、脊线和破碎冰块记录了冰壳受力与重塑的历史，短期观测中地貌保持稳定。",
    caption: "木卫二冰壳",
    detail: "旅行者号合成地图 / 色彩经过处理",
    source: "jupiter/moons/europa/",
  },
  {
    ...rock,
    id: "ganymede",
    name: "木卫三",
    english: "GANYMEDE",
    category: "木星 / 冰质卫星",
    parent: "jupiter",
    color: "#b0a69b",
    texture: "ganymede",
    radius: 0.57,
    orbit: 8,
    period: 7.155,
    orbitPhase: 3.9,
    inclination: 0.2,
    description:
      "太阳系最大的卫星，比水星还大。古老暗区与年轻的沟槽亮区相互交织，它还拥有自身的磁场。",
    facts: [
      ["平均半径", "2,631", "km"],
      ["绕木周期 · 约", "7.15", "天"],
      ["所属天体", "木星", ""],
      ["卫星大小", "最大", ""],
    ],
    feature: "明暗地形与沟槽",
    featureText:
      "暗色地形保留密集撞击坑，明亮区域中的成组沟槽反映了冰壳曾经历的变形。",
    caption: "木卫三地貌",
    detail: "旅行者号合成地图 / 明暗地形",
    source: "jupiter/moons/ganymede/",
  },
  {
    ...rock,
    id: "callisto",
    name: "木卫四",
    english: "CALLISTO",
    category: "木星 / 冰质卫星",
    parent: "jupiter",
    color: "#9e978e",
    texture: "callisto",
    radius: 0.53,
    orbit: 10,
    period: 16.689,
    orbitPhase: 5.1,
    inclination: 0.28,
    description:
      "一颗布满撞击坑的古老卫星。明亮冰质坑壁点缀深色表面，巨大的多环盆地仍清晰可辨。",
    facts: [
      ["平均半径", "2,410", "km"],
      ["绕木周期 · 约", "16.7", "天"],
      ["所属天体", "木星", ""],
      ["表面特征", "密集撞击坑", ""],
    ],
    feature: "多环盆地与古老冰壳",
    featureText:
      "瓦尔哈拉盆地周围的同心环结构源自巨大撞击，冰壳保存了漫长的撞击记录。",
    caption: "木卫四古老表面",
    detail: "旅行者号合成地图 / 撞击盆地",
    source: "jupiter/moons/callisto/",
  },
  {
    ...rock,
    id: "enceladus",
    name: "土卫二",
    english: "ENCELADUS",
    category: "土星 / 活跃冰卫星",
    parent: "saturn",
    color: "#dbe8eb",
    texture: "enceladus",
    high: "4k_enceladus.jpg",
    radius: 0.28,
    orbit: 6.3,
    period: 1.37,
    orbitPhase: 0.35,
    inclination: 0.01,
    description:
      "小巧而明亮的冰世界。南极裂缝喷出水蒸气和冰粒，冰壳下面存在全球性的液态海洋。",
    facts: [
      ["平均半径", "252", "km"],
      ["绕土周期 · 约", "1.37", "天"],
      ["所属天体", "土星", ""],
      ["主要活动", "南极喷流", ""],
    ],
    feature: "虎纹裂缝与冰粒喷流",
    featureText:
      "南极虎纹裂缝附近的喷流持续向外输送物质，也为土星 E 环补充冰粒。",
    caption: "土卫二冰壳",
    detail: "卡西尼号地图 / 南极喷流为动态示意",
    source: "saturn/moons/enceladus/",
  },
  {
    ...rock,
    id: "titan",
    name: "土卫六",
    english: "TITAN",
    category: "土星 / 大气卫星",
    parent: "saturn",
    color: "#d6b777",
    texture: "titan",
    radius: 0.57,
    orbit: 9.2,
    period: 15.945,
    orbitPhase: 3.3,
    inclination: 0.35,
    description:
      "浓厚的氮气大气与橙色雾霾包裹着土星最大的卫星。寒冷地表有由液态甲烷和乙烷形成的湖海。",
    facts: [
      ["平均半径", "2,575", "km"],
      ["绕土周期 · 约", "15.9", "天"],
      ["所属天体", "土星", ""],
      ["大气主要成分", "氮气", ""],
    ],
    feature: "高空雾霾与大气环流",
    featureText:
      "雾霾遮挡可见光中的地表，甲烷在大气与地面之间参与类似水循环的过程。",
    caption: "土卫六大气",
    detail: "JPL 雾霾外观示意 / 非地表影像",
    closeName: "观测大气",
    source: "saturn/moons/titan/",
  },
  {
    ...rock,
    id: "triton",
    name: "海卫一",
    english: "TRITON",
    category: "海王星 / 逆行卫星",
    parent: "neptune",
    color: "#c9c5bc",
    texture: "triton",
    radius: 0.38,
    orbit: 4.4,
    viewUv: [0.49, 0.72],
    period: 5.877,
    orbitPhase: 1.8,
    inclination: 23.2,
    retrograde: true,
    description:
      "海王星最大的卫星，沿与海王星自转相反的方向运行。冰冻表面保留着极冠、奇特地形与暗色条带。",
    facts: [
      ["平均半径", "1,353", "km"],
      ["绕海周期 · 约", "5.88", "天"],
      ["所属天体", "海王星", ""],
      ["轨道方向", "逆行", ""],
    ],
    feature: "氮冰极冠与古老喷流痕迹",
    featureText:
      "旅行者 2 号曾观测到喷流。这里展示其冰质地貌与日照变化，黑色区域没有影像覆盖。",
    caption: "海卫一冰冻表面",
    detail: "旅行者 2 号地图 / 黑色区域缺测",
    source: "neptune/moons/triton/",
  },
  {
    ...rock,
    id: "charon",
    name: "冥卫一",
    english: "CHARON",
    category: "冥王星 / 天然卫星",
    parent: "pluto",
    color: "#b9b0aa",
    texture: "charon",
    radius: 0.36,
    orbit: 2.7,
    viewUv: [0.48, 0.67],
    period: 6.387,
    orbitPhase: 2.8,
    inclination: 0,
    description:
      "冥王星最大的伴星，与冥王星互相潮汐锁定。红褐色北极区、深长峡谷和明亮平原共同构成了它的面貌。",
    facts: [
      ["平均半径", "606", "km"],
      ["绕行周期 · 约", "6.39", "天"],
      ["所属天体", "冥王星", ""],
      ["自转状态", "潮汐锁定", ""],
    ],
    feature: "红色极区与巨大峡谷",
    featureText:
      "北极的深色物质与赤道附近的峡谷系统，记录了冰质表面复杂的演化历史。",
    caption: "冥卫一地表",
    detail: "新视野号影像 / NASA 展示地图",
    source: "dwarf-planets/pluto/moons/charon/",
  },
].map((body) => ({ ...body, group: body.parent ? "moons" : "others" }));
